allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msw: false
  prisma: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  mysql2: ^3.24.5
